title: something
logo: assets/future.jpeg
description: 改善 | Perpetual Self-Evolution | Judith Urbina
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
nav:
  - title: "Home"
    url: "/"
  - title: "Live Sessions"
    url: "/live-sessions/"
  - title: "Data Visualization Project"
    url: "/mini-datavisualization-showcase/"
